### ISSUE TITLE
A possible idea for viewing Sv at different frequencies/periods through slidebars

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#10]
## Questions
It's for the third in > https://github.com/OSOceanAcoustics/echoshader/issues/6#issuecomment-1064600486

 In hvplot.line, we can set groupby="time.day" or groupby="time.week" to add a slidebar for selecting certain time. 
![image](https://user-images.githubusercontent.com/56751303/158019982-f5ad06ec-f374-4349-be95-3c408205dffc.png)
But for the MVBS, which uses hvplot.image, it can't set groupby="ping_time.day". That will report errors. And setting groupby="ping_time" doesn't make any sense.
![Snipaste_2022-03-12_21-40-44](https://user-images.githubusercontent.com/56751303/158020322-0238a554-ac13-44d1-b735-9a37e152850c.png)
 In the above picture, I just set x-axis="frequency" to show it can work, leave it. 
If we want to show one day or one week's MVBS, we can add a Coordinate called "time_range" to help set a cycle we want to show. "time_range" can represent a day or a week. Its values are consistent with "ping_time". 
`mvbs_plot = ds_MVBS.sel(frequency=200000).hvplot.image(x='ping_time',y='depth', groupby='time_range',
    color='Sv', 
    cmap='jet', clim=(-80, -30)
).options(invert_yaxis=True)`
That may help add two sidebars to select the date and frequency

**Comment by ldr426** [comment]
I will look for some solutions in holoviews too.

**Comment by ldr426** [comment]
If using hvplot to draw xarray image diagram, it can only choose two coordinates for x-axis and y-axis respectively. But other coordinates that are not selected for the diagram will automatically add according sidebars. (If we pick a different, lower dimensional plot type (such as a ‘line’) it will automatically apply a groupby over the remaining dimensions.) And it cannot choose time coordinate both as x-axis and slidebar option at the same time like xarray line diagram, probably because dynamic loading will cause conflicts. So if we wanna show different days' Sv, we can add one more coordinate on behalf with the day or the week we want to check.

**Comment by ldr426** [comment]
I have not yet studied Panel. It will combine the map and Sv diagram, I think.

**Comment by leewujung** [comment]
> It can help combine the map and Sv diagram

#18  😄

**Comment by ldr426** [comment]
> I think

After studying panel, I start to know there is no need to change Sv data structure.
