### ISSUE TITLE
Update `requirements`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#110]
The echoshader package requirements are likely a bit outdated since it's been a while, and there are also two files (`requirements.txt` and `new_requirements.txt`)  co-existing at the moment. Let's update and consolidate the requirements, probably into:
- `requirements.txt`: what echoshader actually requires
- `requirements.dev`txt: what is needed to develop echoshader

Related to #109.

**Comment by ldr426** [comment]
Has been solved in https://github.com/OSOceanAcoustics/echoshader/pull/131
