### ISSUE TITLE
Simplify echogram <--> map/curtain by removing the control direction select

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#126]
@leewujung  and @ldr426  discussed on 07/12/2023 that it would be more intuitive to use the echogram <--> map/curtain functionality _without_ control direction select. So that user only needs to worry about the `update_echogram_button` and `update_positions_button`). 

_Originally posted by @leewujung in https://github.com/OSOceanAcoustics/echoshader/pull/122#discussion_r1262760379_

**Comment by leewujung** [comment]
Just to add more detail to this, from https://github.com/OSOceanAcoustics/echoshader/pull/122#pullrequestreview-1528971852:
> * `link_to_track`  and `link_to_echogram` are used in the methods `echogram` and `positions` to link the echogram with the map along with the menu selector `self.link_mode_select` -- I think the logic can be worked out to completely remove this menu selector so that users can just work with buttons `update_echogram_button` and `update_positions_button`

**Comment by ldr426** [comment]
Erase `update button` but still reserve directional select to make the logic clear in https://github.com/OSOceanAcoustics/echoshader/pull/131

**Comment by valentina-s** [comment]
This now is handled with track/echogram control mode without buttons. Closing for now. It can be revisited if a smoother implementation is found.
