### ISSUE TITLE
Disassociate echogram and map + curtain functionalities

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#129]
From https://github.com/OSOceanAcoustics/echoshader/pull/122#pullrequestreview-1528971852
> - the map and curtain functionalities should not be in the Echogram class; they should remain accessible through the accessor approach though -- this will require careful design work
> - many of the param.depends components seem can be moved out of the methods so that they can be specified by the users (and we need to supply clear documentations for how they should be used)

**Comment by ldr426** [comment]
Has been solved in https://github.com/OSOceanAcoustics/echoshader/pull/131
