### ISSUE TITLE
Set up `pre-commit` in the repo

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#13]
This stemmed from discussions in #9:

We can use `pre-commit` and `markdownlint` to check the line length for our markdowns automatically. The same mechanism can then be used to add `black` and `flake8` later once we have code here in this repo.

What @lsetiawan set up in [echopype](https://github.com/OSOceanAcoustics/echopype) are good references:
- https://github.com/OSOceanAcoustics/echopype/blob/main/setup.cfg
- https://github.com/OSOceanAcoustics/echopype/blob/main/.pre-commit-config.yaml

**Comment by lsetiawan** [comment]
Should do `codespell` also 😄
