### ISSUE TITLE
Set up Notebook Examples of different configurations (with refactored syntax)

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoshader#135]
- [x] Echogram Plotting
      - multiple frequency, tricolor, colormap, Sv_range_slider, example of passing parameters
- [x] Echogram and Map plotting, example with changing tiles
- [x] Curtain plotting on its own, example changing aspect ratio, echogram and curtain
- [x] Echogram and stats plotting

@ldr426 add extra possible configurations for each case.

**Comment by ldr426** [comment]
Thanks @valentina-s, Coding was done just. Let me start documents and demos work.
