### ISSUE TITLE
Can not get correct inverting y-aixs in the current holoviews(v1.17.0)

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#136]
As stated in https://github.com/holoviz/holoviews/issues/5727.

We can set default value: `invert_yaxis = True` after this bug fixed.

**Comment by leewujung** [comment]
See https://github.com/OSOceanAcoustics/echoshader/pull/108/commits/59f5e26e2f0dc77a093d5e0906260c0609f234f9 om #108 for temp forced fix.
