### ISSUE TITLE
Deploy docs to RTD for easy viewing online

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#22]
Now that we have a `docs` folder. Let's deploy to Read the docs so that it's all consolidated and can easily be viewed.

**Comment by leewujung** [comment]
I just set up RTD: https://readthedocs.org/projects/echoshader/
and added both of you @lsetiawan @emiliom as maintainers also.

**Comment by lsetiawan** [comment]
Thanks @leewujung! That looks great! Did you activate the PR previews also?

**Comment by leewujung** [comment]
Just did on your prompt!

**Comment by leewujung** [comment]
Seems that this is ready to be closed. 😀
