### ISSUE TITLE
A prototype of echoshader GUI

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#27]
## Ideas
It is a prototype of echoshader GUI.
![Snipaste_2022-03-22_15-24-07](https://user-images.githubusercontent.com/56751303/159429524-68aceeae-d2d8-459b-88f0-3ad9abe59494.png)

### Main area 
This area is main area of the application. It plots and offers description.
![image](https://user-images.githubusercontent.com/56751303/159430930-c0d92980-85b2-4d18-a97b-d2d338d8bf73.png)

There is a tab for different needs.
Overview:https://github.com/OSOceanAcoustics/echoshader/issues/17#issue-1168669060
Analyze: https://github.com/OSOceanAcoustics/echoshader/issues/17#issue-1168669060 and https://github.com/OSOceanAcoustics/echoshader/issues/20
Geospatial data:https://github.com/OSOceanAcoustics/echoshader/issues/18#issue-1168692706 and https://github.com/OSOceanAcoustics/echoshader/issues/26#issue-1169037627 Folium is a good map library for this. 
User guide: Description, necessary explanation and user guide
![image](https://user-images.githubusercontent.com/56751303/159431476-95f9077f-3b1b-417f-bc6a-a398532a07ef.png)

### Sidebar
Users can configure different variables in this area, like which date or color map to select. We can add more customization later, like line width or window type for histogram.
![image](https://user-images.githubusercontent.com/56751303/159432470-5c1061dd-f58f-40ca-9e31-3c7814692ce6.png)

This logo is actually a hyperlink. Users can click it to visit echoshader's official website.
![image](https://user-images.githubusercontent.com/56751303/159432570-3f0d97f5-099d-4db7-8580-392b32083b0e.png)

**Comment by ldr426** [comment]
Or main area can be divided into three or more sub-areas

**Comment by leewujung** [comment]
Thanks @ldr426! 
I think for echoshader our goal is to create the elements ("widgets") that a user can select and put together their own "customizable GUI" (or a better word is probably "dashboard" in Panel language). 

So, it does go with what you have laid out above in terms of what can go where, but we want users to be able to customize it based on their own needs, and we don't decide that for them. Or, they could simply use these widgets in a Jupyter notebook (i.e. outside of a Panel dashboard). 

Does this make sense?

**Comment by ldr426** [comment]
@leewujung
Got it :smile:. Users can call related API to plot what they want in Jupyter notebook. Sometimes, even combined charts. So we don't need an integrated panel dashboard.
There is no essential difference between showing widgets in Jupyter and Panel dashboard. But Panel dashboard is good for server deployment and prettier layout.

**Comment by leewujung** [comment]
Yes! And I should say that there's nothing wrong with you laying out a dashboard though. That would be really nice demo of the capability!

**Comment by ldr426** [comment]
@leewujung  
Thanks, mentor Lee!
It is also a very nice training for me to learn and use more about Panel. :runner:

**Comment by lsetiawan** [comment]
This idea is superseded by the idea of creating widgets rather than full GUI for users. Closing this as stale.
