### ISSUE TITLE
Plotly/HoloViz/FiftyOne widget suggestions + bug list 

### ISSUE THREAD

**Issue by dissagaliyeva** [OSOceanAcoustics/echoshader#32]
Hi everyone! I think I'm a little late for the party :) 

I'm both super excited and terrified to be *hopefully* joining this project! 

After playing around with the functionality, I saw that from raw to cleaned files, lat/long get lost on the way. I was going to suggest a workaround to use them for coordinate representations but I see all of the information is covered already in #26 

Expanding on #18 and #27, there are two solutions that would be beneficial for echoshader's advancement. The **first** one would benefit from dynamic closeable tabs. The two tab versions are from VoloViz & select option from plotly:
1) [Dynamic tabs](https://panel.holoviz.org/gallery/layout/dynamic_tabs.html)
2) [Closable tabs](https://panel.holoviz.org/reference/layouts/Tabs.html#closable)
3) [Plotly selection](https://plotly.com/python/v3/selection-events/)

It’s essentially built on top of @[ldr426](https://github.com/ldr426) idea explained in #27. 

The idea is the following: In the first tab have a map of the world (or of a specific location) along with sonar data from the surface view as explained in issue #17. It would have several functionalities: select region, time, and ping (or anything that is found useful). Here we would have the functionality of selecting as shown here using [Plotly selection](https://plotly.com/python/v3/selection-events/)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/80033932/163115151-e5f7ed0e-c99c-496a-9720-ba158df71cdf.gif)

The second tab would show the characteristics and necessary information as explained in #18. The idea is to have dynamic tabs so that it would have the flexibility to select as many or as few regions as necessary to have a direct comparison. When the user is done exploring the specifics, they can simply close them. Also, if necessary save them as an image. 

It would essentially look like this:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/80033932/163122764-222a63ee-8974-4e67-90db-8ca5d65e0170.gif)

=====

The second solution will require a lot of work but will give a better result in the end (in my opinion). There's such a package called [fifty-one](https://voxel51.com/docs/fiftyone) that primarily deals with computer vision tasks. What is cool about this app is that it can solve A LOT OF tasks and has a great interface that can be re-programmed to our needs. Moreover, it doesn't run on another page but has an interactive widget. There's a pretty big degree of freedom that doesn't limit users, and as suggested in issue #27, it's the main goal. 

The bad news is that it works only with images, so it's not going to be directly applicable. So, we could essentially create an app in the same fashion but tailored for our needs, of course. Here are a couple of links to check out the app:
1. [Notebook to understand how it works](https://colab.research.google.com/github/voxel51/fiftyone-examples/blob/master/examples/quickstart.ipynb)
2. [Functionalities](https://voxel51.com/docs/fiftyone/recipes/index.html)

=====

Some bugs I found along the way:

1. **Broken link**
**Where**: [link](https://echopype.readthedocs.io/en/stable/why.html) 

**Under**:
> echopype contains tools for converting data from various manufacturer-specific formats into a standardized [netCDF]() files

**The broken link**: [link](https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_introduction.html)

=====

2. **Missing NumPy dependency** 
**Where**: [link](https://github.com/OSOceanAcoustics/echopype-examples/blob/main/notebooks/echopype_tour.ipynb)

When downloading with `git clone` and setting up the environment, the code breaks when running the following block:
```
MVBS_ds["Sv"].hvplot.image(

    x='ping_time', y='range', 

    color='Sv', rasterize=True, 

    cmap='jet', clim=(-80, -50),

    xlabel='Time (UTC)',

    ylabel='Depth (m)'

).options(width=500, invert_yaxis=True)
```

**Error message**: `ImportError: Datashading is not available` & `ImportError: Numba needs NumPy 1.20 or less`

=====

3. **Wrong setup directory**
**Where**: [link](https://github.com/OSOceanAcoustics/echopype-examples)

The README.md file contains the line `conda env create -f environment.yml` but the `environment.yml` file is in the `binder` folder.
It should be replaces with `conda env create -f binder/environment.yml`

=====

There is one functionality in fifty-one that lets us use geospatial data with this package, so I'll experiment with it and give feedback afterward along with the notebook so that you can easily reproduce the results :) There are going to be several of them that will also test the first suggestion!

Please let me know if any of these ideas are applicable! 

P.S., I’m super excited to meet you all! And sorry for a huge message😅

**Comment by ldr426** [comment]
>It’s essentially built on top of @[ldr426](https://github.com/ldr426) idea explained in https://github.com/OSOceanAcoustics/echoshader/issues/27.

:smile: Thank you for rebuilding my idea, Dinara. But this idea has been abonded. We don't need to create a certain template for users in echoshader. Users can select panel components to combine what they want. Creating some interactive APIs would be better than a template.

>Error message: ImportError: Datashading is not available & ImportError: Numba needs NumPy 1.20 or less

By the way, the error could come from your environment. It runs without error in my jupyter. Datashading is a package for visualizing big data in the holoviz ecosystem. You could pip install datashader and NumPy == 1.20.

Hope you can have some good results using the package [fifty-one](https://voxel51.com/docs/fiftyone) :)

**Comment by dissagaliyeva** [comment]
Hi @ldr426, thanks for the reply! that's interesting, I had no idea the idea for the panel had been abandoned already. 

> By the way, the error could come from your environment. It runs without errors in my jupyter. Datashading is a package for visualizing big data in the holoviz ecosystem. You could pip install datashader and NumPy == 1.20.

Yup, I was simply referencing that numpy was missing in the requirements.txt file :) 

> Hope you can have some good results using the package [fifty-one](https://voxel51.com/docs/fiftyone) :)

Thank you! And you as well, hope everything is going well with that API you're working on!

**Comment by lsetiawan** [comment]
Hi @dissagaliyeva, could you tell me a little bit about your working environment. What operating system are you using? Also for your conda environment, what python version are you on? Thank you.

**Comment by dissagaliyeva** [comment]
Hi @lsetiawan! Sure, I'm on Windows 10 and Python version 3.9.7

**Comment by emiliom** [comment]
> echopype contains tools for converting data from various manufacturer-specific formats into a standardized [netCDF](https://github.com/OSOceanAcoustics/echoshader/issues/32) files
>
> The broken [link](https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_introduction.html): link

Thanks for reporting this broken link. We'll fix it soon. In the meantime, you can find a lot of information about netCDF online, but the netcdf web site is https://www.unidata.ucar.edu/software/netcdf/. In practice, you will be using a higher-level Python library to interact with netcdf files, especially xarray. This [xarray User Guide page](https://docs.xarray.dev/en/stable/user-guide/data-structures.html) is a nice and compact introduction to the data structure.

**Comment by dissagaliyeva** [comment]
@emiliom thank you for the info!

**Comment by leewujung** [comment]
Hey @dissagaliyeva, welcome!

> that's interesting, I had no idea the idea for the panel had been abandoned already.

I wanted to chime in here on the overall idea. The panel idea actually has _not_ been abandoned, it just takes a form that’s perhaps different from the regular web portals.

What we aim to create in echoshader is a suite of “widgets” that can be mixed and matched by users to configure their own visualization dashboards using the [Panel](https://panel.holoviz.org/) library. This is because regular researchers may not necessarily have the human resources to help deploy and maintain their own front and backend services, so we want to enable some more flexible and convenient data viz capability that can be used in a Jupyter notebook for example. 

This does mean that we need to provide the data linkage between these widgets since the interactions often would require slicing based on specific coordinates. For these “under the hood” data handling operations we need to make decisions on whether it goes in echoshader here or [echopype](https://github.com/OSOceanAcoustics/echopype). So some planning and more discussions are needed on this front.

**Comment by dissagaliyeva** [comment]
Hi @leewujung! 

Sorry, it took me some time to understand how to make an inline working prototype for the idea. Essentially, I was following the prototype I've had in mind:
![image](https://user-images.githubusercontent.com/80033932/164946409-55805f3e-c206-470f-855a-1d16df515e82.png)


The prototype ended up being similar to the idea,  but there were two changes along the way:
1) I couldn't figure out how to combine dynamic and closable tabs on the same line. I think there's no option to do so. Therefore, I've used the following temporary solution (the two tabs have the maps as a placeholder for now):
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/80033932/164946488-e2585cca-c1e8-471d-8880-4cabdd74df63.gif)

I'm thinking of showing the results in a separate tab so as not to clutter the space. Currently, I'm not a big fan of the hanging plot underneath the setting and a map. Therefore, I'm thinking of putting all of the resulting plots in the "Results" tab. To give a better user experience, I'm also considering giving the names according to the selected dates/times. 

2) I can't decide between a dropdown and a [RadioBoxGroup](https://panel.holoviz.org/reference/widgets/RadioBoxGroup.html), so both implementations are present in the notebook. 

===

A couple of things to know about the prototype:
1) It has a date and time picker. I've made it in a way that you can only see and select the days/times that are present in the *.nc files. Even though the day gets selected, the timing is a bit off, so it will need additional tweaking.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/80033932/164946802-55c748f0-df90-40dc-bcaf-a39418fc4a51.gif)

2) A frequency map is dynamic and reacts to the selected frequency as intended. Frequencies are also created depending on the *.nc files parameters, that means if a file has 3000 and 5000, it will only have those two values. 
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/80033932/164946881-6b84434d-2fcb-4e40-936a-406de3425ff4.gif)

3) There are some additional functions created. The descriptions are below, for convenience they're also present in the notebook. 

- **combine_data**

This function takes in all the \*.nc files and combines them. The problem with `ep.combine_data` function is that it doesn't catch the errors when given inappropriate data formats. That is especially evident if there are files like `Summer2017-D20170625-T190753_Sv.nc` (**that end with _Sv**) and `Summer2017-D20170625-T190753.nc`. 

For my purpose, I've created a separate function that ignores files with no latitude/longitude and combines all of the rest. For now, there are no explicit tests created, it's just a working prototype for the current data in hand. I'll be using lat/lon to create a GeoPandas & further create visualizations for maps and frequencies. 

- **get_geo & compute_mvbs**

The `get_geo` function creates a DataFrame that holds lat/lon as used in <a href="https://github.com/OSOceanAcoustics/echopype-examples/blob/main/notebooks/echopype_tour.ipynb">echopype_tour</a>. The other takes advantage of the `ep.calibrate.compute_Sv` functionality but created as a function to overcome redundancy. 

- **show_freq**

This function shows the maps depending on the selected frequencies. 

- **get_map**

This function creates a map that holds all of the traces using Plotly. Ideally, this function will have the capabilities to select using both box-select and lasso-select. For now, the function simply shows the map interactively. 

====

### Problems

There's only one problem that I'm facing. I can't solve the box- and lasso-select for now. Since there's Plotly's map to show the route, both selection options are already there but they're not reactive yet. This one will need more time. 


The implementation and dataset are available here: https://github.com/dissagaliyeva/echoshader
For now, there are no tests, but they'll be added within the next few days :)

**Comment by lsetiawan** [comment]
We have selected a contributor and now in a working phase. Closing this issue. Thank you all for your thoughts and ideas in the brainstorm phase.
