### ISSUE TITLE
New ability to visualize Sv data as echograms

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#37]
## Overview

Echoshader needs the ability to plot Sv data as echogram so that users can explore their datasets for multiple dates and channels/frequencies, using various colormaps.

### Expected Results

Users can view their raw data as Sv or MVBS. Also users can control the timespan, frequency/channels, and colormap. The plot should be dynamic so that users can zoom in and out or pan to get a sense of what's going in the water column.

### Related issues

- #17 
- #21
- #42
- #34
- #43

<details>
<summary><h3>Proposed idea</h3></summary>

### For visualizing sonar data as a stack of cards in https://github.com/OSOceanAcoustics/echoshader/issues/17#issue-1168669060

- **Component 1** : [DatetimeRangePicker](https://panel.holoviz.org/reference/widgets/DatetimeRangePicker.html#widgets-gallery-datetimerangepicker).  Control the time span.
<img src="https://user-images.githubusercontent.com/56751303/164282921-6d345bb4-17e8-47cd-bc86-628db6d9e38f.png" width="300px">

- **Component 2** : [Select](https://panel.holoviz.org/reference/widgets/Select.html). Choose specific frequency and colormap.
<image src="https://user-images.githubusercontent.com/56751303/164284087-3f5dbf46-cfed-43e6-be5a-1ac3f9922fcb.png " width="400px">

- **Component 3** : [RangeSlider](https://panel.holoviz.org/reference/widgets/RangeSlider.html#widgets-gallery-rangeslider) :  Control depth range in bird's eye view image. 
![image](https://user-images.githubusercontent.com/56751303/164944098-72af11cd-cb27-42c9-bc2b-a001eb164598.png)

- **Component 4** : [ArrayInput](https://panel.holoviz.org/reference/widgets/ArrayInput.html#widgets-gallery-arrayinput). Customize colormap input.
<image src="https://user-images.githubusercontent.com/56751303/164286861-07bb0a1a-8074-423f-980c-ca8bcc64a331.png" width="400px">

- **Component 5** : [ToggleGroup](https://panel.holoviz.org/reference/widgets/ToggleGroup.html#widgets-gallery-togglegroup) : Toggle between slice image and bird's-eye view image.
![image](https://user-images.githubusercontent.com/56751303/164946075-a7816f2a-eff8-4c24-a423-049050929424.png)
### Prototype 
made by balsamiq

#### Slice diagram
![image](https://user-images.githubusercontent.com/56751303/164943569-64f7513b-6236-46f3-9590-cbdd199b96c7.png)
#### Bird's-eye view
![image](https://user-images.githubusercontent.com/56751303/164943615-22b2a0f6-a2eb-47b1-8f39-88f06db323d0.png)

_Originally posted by @ldr426 in https://github.com/OSOceanAcoustics/echoshader/issues/34#issuecomment-1104213635_
</details>

## Actions

@ldr426 please create small issues on the various steps that you're going to do to make this happen so that we can track it here. Thank you. Let me know if you have any questions.

**Comment by leewujung** [comment]
I'll close this now since this ability already exists, and we'll focus on refactoring the package structure and improving/benchmarking the performance going forward.
