### ISSUE TITLE
New ability to visualize Sv data as data cube

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#38]
## Overview

Echoshader needs the ability to plot Sv data as echogram data cube so that users can explore their datasets for multiple dates and channels/frequencies, using various colormaps as data cube.

### Expected Results

Users can view their raw data as Sv or MVBS as data cube. Also users can control the timespan, frequency/channels, and colormap. The plot should be dynamic so that users can zoom in and out or pan to get a sense of what's going in the water column through time.

### Related issues
- #17 
- #29
- #42 
- #43 
- #34

<details>
<summary><h3>Proposed idea</h3></summary>

### For visualizing sonar data as a data cube in https://github.com/OSOceanAcoustics/echoshader/issues/17#issue-1168669060

- **Component 1** : [RangeSlider](https://panel.holoviz.org/reference/widgets/RangeSlider.html#widgets-gallery-rangeslider) :  Customize width and height of the cube. 
Width : Selected dates
Height : Depth
<image src="https://user-images.githubusercontent.com/56751303/164289647-57ff9571-c54b-46cc-9cb3-d68ee5cd8318.png" width="300px">

- **Component 2** : [Select](https://panel.holoviz.org/reference/widgets/Select.html). Choose specific frequency and colormap.
<image src="https://user-images.githubusercontent.com/56751303/164284087-3f5dbf46-cfed-43e6-be5a-1ac3f9922fcb.png" width="400px">

- **Component 3** : [ArrayInput](https://panel.holoviz.org/reference/widgets/ArrayInput.html#widgets-gallery-arrayinput). Custom colormap input.
<image src="https://user-images.githubusercontent.com/56751303/164286861-07bb0a1a-8074-423f-980c-ca8bcc64a331.png" width="400px">

### Prototype 
made by balsamiq
![image](https://user-images.githubusercontent.com/56751303/164422831-794c1f7e-ac2a-4a67-9d00-93a469f55d80.png)

_Originally posted by @ldr426 in https://github.com/OSOceanAcoustics/echoshader/issues/34#issuecomment-1104227193_
</details>

## Actions

@ldr426 please create small issues on the various steps that you're going to do to make this happen so that we can track it here. Thank you. Let me know if you have any questions.

**Comment by leewujung** [comment]
Closing this now to declutter, and since the core idea is in #17.
