### ISSUE TITLE
New ability to visualize echogram with ship track

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#39]
## Overview

Echoshader needs the ability to plot Sv data as echogram next to a geographical plot of ship track where sample has been collected so that users can explore their datasets for multiple dates and channels/frequencies, using various colormaps, while knowing the exact location where it was collected. This is very important for the Hake Survey!

### Expected Results

In one panel users can pan a small window on a map where the ship track is plotted, and then
in another panel the corresponding sonar data is displayed.

### Related issues
- #18
- #34
- #43 

<details>
<summary><h3>Proposed idea</h3></summary>

### For Interactive visualization of sonar data and geospatial location in https://github.com/OSOceanAcoustics/echoshader/issues/18#issue-1168692706

- **Component 1** : [Select](https://panel.holoviz.org/reference/widgets/Select.html). Choose specific frequency, colormap and tiles.
Tiles: Square bitmap graphics displayed in a certain kind of grid arrangement to show a map.
![image](https://user-images.githubusercontent.com/56751303/164796038-33b3bee1-5ecf-43a3-a45b-1a216a7f0edf.png)

- **Component 2** : [ArrayInput](https://panel.holoviz.org/reference/widgets/ArrayInput.html#widgets-gallery-arrayinput). Customize colormap input.

- **Component 3** : [TextEditor](https://panel.holoviz.org/reference/widgets/TextEditor.html#widgets-gallery-texteditor). Output geo information like latitude, longitude and time **in a selected box**

- **Editable box in the map**:  Select a box in the map, and show the corresponding Sv image and geo info.

### Prototype 
made by balsamiq
![image](https://user-images.githubusercontent.com/56751303/164793657-eeb0aeb9-7d6d-4620-b67e-cfcfb71fb283.png)

_Originally posted by @ldr426 in https://github.com/OSOceanAcoustics/echoshader/issues/34#issuecomment-1106890566_
</details>

## Actions

@ldr426 please create small issues on the various steps that you're going to do to make this happen so that we can track it here. Thank you. Let me know if you have any questions.

**Comment by leewujung** [comment]
I'll close this now since most of the capabilities required here already exist, and we'll focus on refactoring the package structure and improving/benchmarking the performance going forward.

An unmet requirement is #47.
