### ISSUE TITLE
New ability to visualize echogram as 3D curtain plot along ship track

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#40]
## Overview

Echoshader needs the ability to plot Sv data as 3D echogram curtain plot along a ship track.

### Expected Results

Plot 3D echogram curtain with Sv value, linking 2D aerial view of the ship track. A folium map
element that lets users select the geospatial area or segments, then PyVista panels are used to
generate the 3D curtain plots for the selected areas.

### Related issues

- #26
- #30 
- #34
- #43

<details>
<summary><h3>Proposed idea</h3></summary>

### For 3D echogram curtain along ship track in https://github.com/OSOceanAcoustics/echoshader/issues/26#issue-1169037627
This part can link the aerial view of the ship track in 2D and map with editable box.
We can use editable box in echogram and map to specify the area of this 3D curtain.

- **Component 1** : [Select](https://panel.holoviz.org/reference/widgets/Select.html). Choose specific frequency, colormap.

- **Component 2** : [ArrayInput](https://panel.holoviz.org/reference/widgets/ArrayInput.html#widgets-gallery-arrayinput). Customize colormap input.

- **Component 3** : [TextEditor](https://panel.holoviz.org/reference/widgets/TextEditor.html#widgets-gallery-texteditor). Output geo information like latitude, longitude and time **in a selected box**

- **Component 4** : [Toggle](https://panel.holoviz.org/reference/widgets/Toggle.html).
To do some interesting extends! :smile:
Toggle between showing bathymetry and not 
(see in https://github.com/OSOceanAcoustics/echoshader/issues/26#issuecomment-1079644854)
Toggle between showing underwater vehicle track and not 
(see in https://github.com/OSOceanAcoustics/echoshader/issues/28#issuecomment-1088282857
 and https://github.com/OSOceanAcoustics/echoshader/issues/28#issuecomment-1088570395)

### Prototype 
made by balsamiq
![image](https://user-images.githubusercontent.com/56751303/164945181-01659e5b-970a-4ce2-a47e-d004db541fae.png)

_Originally posted by @ldr426 in https://github.com/OSOceanAcoustics/echoshader/issues/34#issuecomment-1107644888_
</details>

## Actions

@ldr426 please create small issues on the various steps that you're going to do to make this happen so that we can track it here. Thank you. Let me know if you have any questions.

**Comment by leewujung** [comment]
I'll close this now since most of the capabilities required here already exist, and we'll focus on refactoring the package structure and improving/benchmarking the performance going forward.

The dataset used in GSoC 2022 was pretty small for testing the 3D curtain plotting. This summer we should test out larger datasets hosted either locally or on the cloud.
