### ISSUE TITLE
Benchmark package performance

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#41]
## Overview

Echoshader needs to be benchmarked for optimizing performance, especially with the 3D plotting.

### Expected Results

Set up benchmarks to test what performance the APIs have on datasets of different sizes.
Improve algorithms to enhance overall performance and reduce performance gap between small
and big data.

### Related issues

- #42 
- #43

<details>
<summary><h3>Proposed idea</h3></summary>

To benchmark algorithm performance, we will use several datasets with different data sizes:
1. Small data - one day 2. Medium data - one week 3. Large data - one month
Run the program on different datasets with different data sizes according to specified
performance criteria, like runtime and running memory. Go through a number of iterations.
Record average runtime, minimum runtime of each round and the running memory. Statistics
runtime and running memory.

Originally from GSoC proposal by @ldr426
</details>

## Actions

@ldr426 please create small issues on the various steps that you're going to do to make this happen so that we can track it here. Thank you. Let me know if you have any questions.

**Comment by leewujung** [comment]
I'll close this issue now and for upcoming work this summer we'll create smaller issues for benchmarking each viz functionalities separately.
