### ISSUE TITLE
OOI Datasets Requests

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoshader#42]
## Overview

Echoshader will need some datasets for testing its functionality. It would be great if we can use the OOI data from the `CE04OSPS-PC01B-ZPLSCB102` instrument. It would be really cool to see the variations of bioacoustic sonar data from the month of **August, 2017**.

The raw data can be found at https://rawdata.oceanobservatories.org/files/CE04OSPS/PC01B/ZPLSCB102_10.33.10.143/2017/08/.

This [echopype-examples notebook](https://osoceanacoustics.github.io/echopype-examples/ms_OOI_EK60_mooringtimeseries.html) is a good resource to get started.

**Comment by leewujung** [comment]
Now that there are organized datasets and the notebook used to generated them in #92, we can close this issue!
