### ISSUE TITLE
Handle discontinuous time segments when selecting a region of interest from a cruise map and plotting the corresponding echogram.

### ISSUE THREAD

**Issue by valentina-s** [OSOceanAcoustics/echoshader#47]
Since the ship track can take any shape, sometimes a person can select a region which does not correspond to a continuous segment in time so the corresponding echogram will consist of several continuous segments. Consider the selection case in the picture above: there are two continuous segments:
![cruise_map](https://user-images.githubusercontent.com/11621647/177853657-708e3ed8-a06a-45b4-b0a9-76e0303d96aa.png)
(From this echopype [example notebook](https://github.com/OSOceanAcoustics/echopype-examples/blob/main/notebooks/ms_PacificHake_EK60_cruisetracks.ipynb))

One needs to decide how to visualize those segments. To avoid plotting all the segments in separate echogram views, one way is to still have only one echogram viewer but indicate somehow that there is a discontinuity. Two options are described in the figure below:
![DisconnectedEchograms](https://user-images.githubusercontent.com/11621647/177853775-9f7a76a8-948b-48c8-a05e-5edcc4e2047c.jpg)

**Comment by ldr426** [comment]
Has been solved in https://github.com/OSOceanAcoustics/echoshader/pull/131
