### ISSUE TITLE
Juypter notebook crashing when trying to retrieving EK60 echosounder data

### ISSUE THREAD

**Issue by praneethratna** [OSOceanAcoustics/echoshader#68]
### General description of problem
Jupyter notebook crashing when trying to run the data retrieving part of the [notebook](https://github.com/OSOceanAcoustics/echoshader/blob/f65e21893f601b2dfa4d1affdb32f6b88ac13335/docs/source/gsoc/2022/Echogram_EchoStats.ipynb).

### Computing environment
_Required_
- Echoshader version: 0.1.dev142+gf65e218
- How echoshader was installed (e.g., conda or pip): conda
- Operating system: Ubuntu 22.04 via WSL2 on Windows 10

### Minimum example
_Required: A minimum code snippet that reproduces your problem._
The following code reproduces the errors I encountered:
```python
for desired_raw_file_url in desired_raw_file_urls:
    raw_fpath = Path(desired_raw_file_url)
    
    try_times = 0
    while True:
        try_times += 1
        
        if try_times > 2:
            print(f"Failed to process raw file {raw_fpath.name}: {e}.")
            break
        
        try:
            # Access file directly from S3 to create a converted EchoData object in memory
            ed = ep.open_raw(
                f"{desired_raw_file_url}",
                sonar_model='ek60'
            )

            # Use the EchoData object "ed" to generate calibrated and
            # computed MVBS files that will be saved to netcdf
            ds_Sv = ep.calibrate.compute_Sv(ed)

            ds_MVBS = ep.preprocess.compute_MVBS(
                ds_Sv,
                range_meter_bin=1,  # in meters
                ping_time_bin='1800s'  # in seconds
            )

            ds_MVBS.to_netcdf(calibrated_dpath / f"MVBS_{raw_fpath.stem}.nc")
            
            # release to avoid memory overflow
            del ed
            del ds_Sv
            del ds_MVBS
            
            gc.collect()

        except Exception as e:
            print(f"Failed to process raw file {raw_fpath.name}: {e}. Execute again")
            continue
            
        break
```

### Error message printouts
_Required: Copy-paste the entire error messages you encounter here._
Below is the error messages I received when running the above code:
```python
Canceled future for execute_request message before replies were done

The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here for more info. View Jupyter log for further details.
```

### Provide an example file
_Required: An example file that allow reproducing the problem._
- Link to an example raw file: [SOME_ONLINE_LOCATION](https://rawdata.oceanobservatories.org/files/CE04OSPS/PC01B/ZPLSCB102_10.33.10.143/2017/08). Smaller files are strongly preferred (e.g., <25MB for AZFP and EK60, <100MB for EK80).
- Raw file sensor model: (FOR EXAMPLE: Simrad EK60)

### Troubleshooting
_Optional but preferred: Explain any steps that you have taken to identify the cause of conversion error._

**Comment by leewujung** [comment]
I made some small modifications in #71 -- the notebooks did not crash for me but there were likely some memory efficiency issues due to echopype (which is being worked on for v0.7.2). This issue/need for test/benchmarking data generation is tracked in #70, so will close this now.
