### ISSUE TITLE
Cloud platform learning

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#74]

**Comment by leewujung** [comment]
@ldr426 : please put the resources you are reading or have read here.

**Comment by ldr426** [comment]
https://www.notion.so/EC2-faeceebfc16f45509d3f4c18c25f2c22?pvs=4

**Comment by leewujung** [comment]
I think we can close this now! We can create specific issues later when there are specific cloud-related things to take care of.
