### ISSUE TITLE
Test all 2022 echoshader features

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#75]
The first step for getting back to the development is to revamp and test all 2022 echoshader features.

The tests should run both locally and on EC2.

@ldr426 : please list in comments below what you have tested and document what works and what doesn't (and what the problem or suspected problem is if it does not work).

# Functions Tested List
Tesing data:
Ship (10 days, 2017-07-24 to 2017-08-02)
Range meter bin = 5m
Ping time bin = 1800s

## Simple Hist
<img width="979" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/98e60897-2230-48b1-b185-f14f189d0d26">

## Echogram for single gram
<img width="1148" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/2f4be9ee-604f-48b1-9f05-ad66f4924b60">

## Box Select
<img width="1151" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/f2a2d249-2fa5-4189-b448-2f769b9b0df7">

## Echogram for multiple grams
<img width="1140" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/6aff616f-1fbc-4fd0-aaba-a0defddb5d39">

## Statistic Table in Echostats
<img width="1176" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/df6ec4cc-9b98-4a79-95fe-78c5852c327b">
<img width="364" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0915440e-efbe-49e4-a983-c034231a7470">

## Statistic histogram(single, overlay, layout) in Echostats
<img width="623" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/c1437ac3-26ca-4db7-bedb-86b0ad6a0498">

<img width="592" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/7346a37e-e817-4cd6-af18-f8899f24eb29">

<img width="593" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0fb19864-83fa-4bdf-ba91-4b2330ac75e5">

## Map in Echomap
<img width="599" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0e87660e-c891-4fd8-b973-918614a73cef">

## Curtain in Echomap
<img width="747" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/b3009871-14e7-467d-a107-d17501058058">

**Comment by ldr426** [comment]
# Problem 2
When using `invert_yaxis = True`, echogram does not show immediately.
You can see the gram after scrolling down along the y-axis. But the value on the axis is not correct.
<img width="829" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/3666b374-c608-45ee-bbce-16063f251c04">
<img width="791" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/965e17de-fea4-406c-8710-9d9c8d4cb19f">

# Possible Cause
Unknow. The old version does not have this problem.

# Temporary Solution
Do not use option `invert_yaxis`. There must be approach to invert y-axis correctly, which needs to be dived into later.
<img width="825" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/512690ae-7e68-4cb4-b7ea-cde27e8e8526">

**Comment by ldr426** [comment]
# Problem 3
There is no `box select` in tool bar.
<img width="47" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0b1519a2-7522-49a0-a3a6-c874952b18b2">

# Possible Cause
Unknown. In the old version, the tool icon appears in default.

# Solution
[Explicitly claim this tool in options](https://holoviews.org/user_guide/Linked_Brushing.html#javascript-based-linked-brushing)
<img width="558" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/cbb98c0e-7a42-4f54-b64f-2e711b04704e">
<img width="708" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/41370a74-ffc6-405a-bb3a-87443d2de940">

**Comment by ldr426** [comment]
# Problem 4
Errors below appear when running echogram.
<img width="1153" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/bd4d1789-c76d-44d4-af0f-6d3efc29b977">

# Possible Cause
May come from `rasterize`
<img width="535" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/63ce6339-9b8e-4675-a5c8-839eb3657f1a">

# Solution
No impact on running. Not emergent. Need to be checked later.

**Comment by ldr426** [comment]
# Problem 5
Errors below appear when tunning control widgets on panel.
<img width="1142" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/63624abb-95c8-42d2-a6ae-e44bed79efcb">
# Possible Caues
May come from conflict bewtwen different controlled  grams.
One control panel is responsible for multiple grams.

# Solution
No impact much on running. Not emergent. Need to be checked later.

**Comment by ldr426** [comment]
# Problem 6
No color map rendering when plotting 3D curtain.
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/cbb939e8-dd64-48be-b333-6397cdc61953/Untitled.png)

# Possible Caues
Unknown.

# Solution

Problem 5
Errors below appear when tunning control widgets on panel.
image

Possible Caues
May come from conflict bewtwen different controlled grams.
One control panel is responsible for multiple grams.

Solution
No impact much on running. Not emergent. Need to be checked later.

**Comment by ldr426** [comment]
# Functions Tested List
## Simple Hist
<img width="979" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/98e60897-2230-48b1-b185-f14f189d0d26">

## Echogram for single gram
<img width="1148" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/2f4be9ee-604f-48b1-9f05-ad66f4924b60">

## Box Select
<img width="1151" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/f2a2d249-2fa5-4189-b448-2f769b9b0df7">

## Echogram for multiple grams
<img width="1140" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/6aff616f-1fbc-4fd0-aaba-a0defddb5d39">

## Statistic Table in Echostats
<img width="1176" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/df6ec4cc-9b98-4a79-95fe-78c5852c327b">
<img width="364" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0915440e-efbe-49e4-a983-c034231a7470">

## Statistic histogram(single, overlay, layout) in Echostats
<img width="623" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/c1437ac3-26ca-4db7-bedb-86b0ad6a0498">

<img width="592" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/7346a37e-e817-4cd6-af18-f8899f24eb29">

<img width="593" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0fb19864-83fa-4bdf-ba91-4b2330ac75e5">

## Map in Echomap
<img width="599" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/0e87660e-c891-4fd8-b973-918614a73cef">

## Curtain in Echomap
<img width="747" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/b3009871-14e7-467d-a107-d17501058058">

**Comment by ldr426** [comment]
# Problem 7 (Solved)
No `hover` tool when plotting overlay gram+box.
<img width="707" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/88520158-7404-4a84-93ac-9afa722080a5">

# Possible Caues
 Unkown

# Soultion
Explicitly declare `hover` tool in holoviews opt.
<img width="516" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/4d8d8d31-3110-4eef-b2d0-5f651867b4a6">
<img width="613" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/e7b3ec45-c505-43a7-a186-2b97f89609e1">

**Comment by ldr426** [comment]
# Problem 8
No pyvista shown in EC2

# Cause
[ImportError: libGL](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo)
or
https://github.com/pyvista/pyvista/issues/177

# Solution
in Ubuntu 
`sudo apt install libgl1-mesa-glx`
When running jupyter:
``` python
import pyvista
pyvista.start_xvfb()
```
or
https://docs.pyvista.org/version/stable/getting-started/installation.html#running-on-remote-servers

**Comment by Hoxbro** [comment]
Problem 1: is caused by an upstream change in Jupyter, ref: https://github.com/holoviz/holoviews/issues/5699#issuecomment-1569025301. We have tried to reduce this by setting `inline=False` in 1.16.1. 

Problem 4: It seems like a bug in Holoviews. If possible, please report it with a MRE. 

Problem 9: This was a bug in Panel and is fixed in the latest release (1.1).

**Comment by leewujung** [comment]
Great @ldr426 that you have a list of all the problems and causes and solutions for a subset of them in #92. I think we can close this issue now. I'm putting the "good future ref" label so that we can come back to them once the refactoring is done.
