### ISSUE TITLE
Documenting existing echoshader structure

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#77]
To facilitate refactoring the echoshader package, we need a clean documentation of what the current echoshader structure and interaction look like. Please follow the UML diagram conventions and put a few references for the diagrams in the comments below.

### Requirements
- [x] Class diagram and interaction diagram for methods
- [x] Definitions of data input/output format for the classes and methods

@ldr426 : as you work on the above, please put links on the diagrams as comments under this issue.

**Comment by ldr426** [comment]
[Class diagram and interaction diagram for methods](https://drive.google.com/file/d/1eW6uJJre5nuUUSPq8ux0xlmHdzI6ae75/view?usp=sharing)

**Comment by ldr426** [comment]
[Definitions of data input/output format for the classes and methods](https://www.notion.so/Echoshader-Definitions-808e542d92884aaab46edb9969f5eb33?pvs=4)

**Comment by leewujung** [comment]
This issue can be closed now!
