### ISSUE TITLE
Benchmarking different sizes of datasets

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#78]

**Comment by ldr426** [comment]
# Testing env
Instance | vCPU* | CPU Credits / hour | Mem (GiB) | Storage | Network Performance
-- | -- | -- | -- | -- | --
t2.xlarge | 4 | 54 | 16 | EBS-Only | Moderate

# Echogram and EchoStats
For dataset `Moored_range=0.2_ping=60s_start=2017-08-01-00-00_end=2017-08-31-23-59`
Best resolution for **OOI** concatenated data:
CPU times: user 54.6 s, sys: 21.3 s, total: 1min 15s, Wall time: 1min 17s
<img width="420" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/c4584161-d208-4f19-a69c-9be44777eace">

For dataset `Hake_range=0.2_ping=60s_start=2017-07-24-00-00_end=2017-08-02-23-59`
Best resolution for **Hake** concatenated data:
Kernel died when running. Can render echogram but fail to do statistic stuff.

For dataset `Hake_range=0.2_ping=300s_start=2017-07-24-00-00_end=2017-08-02-23-59`
Second best resolution for **Hake** concatenated data:
CPU times: user 21.9 s, sys: 8.92 s, total: 30.8 s
Wall time: 33.4 s
<img width="395" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/ba4cc005-3fac-4f17-960f-5ceeb5f00d6f">

# Echogram and EchoMap
For dataset `Hake_range=0.2_ping=60s_start=2017-07-24-00-00_end=2017-08-02-23-59`
Best resolution for **Hake** concatenated data:
CPU times: user 69.9 ms, sys: 11.3 ms, total: 81.2 ms
Wall time: 79.9 ms
<img width="596" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/6cc14dcb-7e64-4ae9-934f-893ca4eb83d8">

**Cannot render striped curtain.**
Curtain can be displayed with `Hake_range=1_ping=300s_start=2017-07-24-00-00_end=2017-08-02-23-59`:
<img width="553" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/23e43486-51a6-473c-ba93-c9c0a03dbcb7">

**Comment by valentina-s** [comment]
This is done.
