### ISSUE TITLE
Refactor Box select; Lasso(Polygon) Select for Non-Rectangular Region

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#81]
- [x] #117
- [ ] #118
- [x] #119
- [ ] #124

Fisheries scientists collaborate with colleagues to verify species identifications in different regions. However, the current functionality of the system does not allow me to plot a histogram specifically for non-rectangular polygon regions. Therefore, I would like to propose a new feature that enables users to plot a histogram based on a non-rectangular polygon region, allowing to analyze the distribution of "hake" in these areas accurately.

Users should be able to select a non-rectangular polygon region.

Relavant reference: [lasso select in holoviews](https://holoviews.org/user_guide/Linked_Brushing.html#box-select-vs-lasso-select)

**Comment by ldr426** [comment]
Warning appears when plotting real-time bounds from box select in VS Code:
See: https://github.com/holoviz/holoviews/issues/5731

**Comment by leewujung** [comment]
Hey @ldr426 : What do you think if you split this issue into 2: one focuses on using a rectangular area (a box) and the other focuses on using a polygon area, with each of them having the (a) selection and (b) data export component? This way in the current Refactoring milestone you could just focus on the box one, and push the polygon one to the next milestone?

**Comment by valentina-s** [comment]
This is issue was split and the remaining parts about polygon select are separate issues now #118, #124. So closing!
