### ISSUE TITLE
Refactor Echogram(s); Tricolor Echogram for Distinguishing Fish Species

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#82]
- [x] **Refactor**: As a fisheries scientist, John wants to scroll through an echogram consisting of one transect of echosounder data (ship: hake survey), so that he can see where dense aggregations of fish may be. Can get turned OFF some time.
- [x] **Refactor**: As an oceanographer, Amy wants to scroll through an echogram consisting of multiple months of echosounder data from a mooring (OOI), so that she can see if the zooplankton daily movements have changed over a long period of time. On for 24/7. 
- [x] **To do**: As a fisheries scientist, John wants to plot the “tricolor” echogram, which maps 3 frequencies to RGB color, so that he can distinguish the fish species.

Fisheries scientists often work with echogram data to analyze fish species composition. To improve the accuracy of species identification, I would like to propose a new feature that allows users to plot a "tricolor" echogram. This gram would map three different frequencies to RGB colors, providing a visual representation that helps distinguish between different fish species.

Refactor: https://github.com/OSOceanAcoustics/echoshader/issues/17
Echoshader should provide an option to generate a tricolor echogram overlay by mapping the selected frequencies to RGB colors. The result should be displayed on the echogram, with different colors representing different frequency bands.

Ref: https://colab.research.google.com/drive/1v_ldJWGN20XLThLUioaymBrpfoXxeniR#scrollTo=VAbfnHM9vstR

**Comment by ldr426** [comment]
X-coordinate cannot show correctly in RGB
<img width="173" alt="image" src="https://github.com/OSOceanAcoustics/echoshader/assets/56751303/08cd06c0-9cfb-451d-a450-71b7178e0d11">

**Comment by leewujung** [comment]
The core of this issue (the 3 functionalities) are addressed in PR #93. Additional refinement are recorded in new issues, so I'll close this one now.
