### ISSUE TITLE
Refactor Histograms; Histograms for Non-Rectangular Region

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#94]
- [x] #115
- [x] #116
- [ ] #114

Refactor: https://github.com/OSOceanAcoustics/echoshader/issues/20
Users should be able to select a non-rectangular polygon region to create hists and statistic tables.

**Comment by leewujung** [comment]
Will also be a good idea to separate out these "user stories" into different issues, especially between the box and the polygon cases.

**Comment by valentina-s** [comment]
Histograms are refactored in #146. Polygon selection is separated in its own issue: #114. Closing!
