### ISSUE TITLE
Detach echograms linking between different examples

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#99]
Single frequency and multiple frequency plots are linked, but tricolor is not: maybe best not to link them since they are three different examples, not one widget.

_Originally posted by @valentina-s in https://github.com/OSOceanAcoustics/echoshader/issues/93#issuecomment-1593464767_

**Comment by leewujung** [comment]
I think that different layouts should just be different widgets, and we can provide example notebooks to show people how to link them?

**Comment by ldr426** [comment]
Has designed the pattern that unifed all echograms(including tricolor echogram) behaviors in https://github.com/OSOceanAcoustics/echoshader/pull/13
